[/Script/BuildSettings.BuildSettings]
DefaultGameTarget=ZeroDawn

[URL]
; Steam P2P
Protocol=steam

[OnlineSubsystem]
DefaultPlatformService=Steam

[OnlineSubsystemSteam]
bEnabled=true
SteamDevAppId=480

[/Script/Engine.Engine]
bSmoothFrameRate=true
SmoothedFrameRateRange=(LowerBound=(Type=Inclusive,Value=30.000000),UpperBound=(Type=Inclusive,Value=144.000000))

[/Script/Engine.GameEngine]
bUseFixedTimeStep=false

[/Script/Engine.UserActivityTracker]
bIsEnabled=true

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=True
r.DefaultFeature.MotionBlur=True
r.DefaultFeature.LensFlare=True
r.DefaultFeature.AmbientOcclusion=True
r.DefaultFeature.AmbientOcclusionStaticFraction=True
r.DefaultFeature.Bloom=True
r.DefaultFeature.MotionBlur=True
r.MotionBlurQuality=4
r.DepthOfFieldQuality=3
r.LensFlareQuality=2
r.SceneColorFringeQuality=1
r.AmbientOcclusionLevels=2
r.ShadowQuality=5
r.Shadow.CSM.MaxCascades=4
r.Shadow.MaxResolution=2048
r.Shadow.RadiusThreshold=0.03
r.Shadow.DistanceScale=1.0
r.StaticMeshLODDistanceScale=1.0
r.MipMapLODBias=0
r.MaxAnisotropy=16
r.Tonemapper.GrainQuantization=1
r.PostProcessing.PropagateAlpha=0
r.DefaultFeature.AntiAliasing=2
r.PostProcessingAAQuality=6

[/Script/Engine.StreamingSettings]
s.AsyncLoadingThreadEnabled=True
s.WarmUpLoadingTime=4
s.bStaticComponentsUseSlowStreaming=True
s.bAllowLevelStreamingRequestsWhileExiting=TRUE

[/Script/Engine.GarbageCollectionSettings]
gc.TimeBetweenPurgingPendingKillObjects=60.000000

[/Script/Engine.AudioSettings]
DefaultReverbApply=true
bAllowVirtualAmbientSounds=true
bUseAudioThread=true

[/Script/Engine.Console]
ConsoleKey=Tilde
MaxScrollbackSize=1024

[/Script/EngineSettings.GeneralProjectSettings]
ProjectName=Zero Dawn: Modern Warfare
CompanyName=Zero Dawn Studios
ProjectVersion=1.0.0
bUseBorderlessWindow=True

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=49DE27AE3DD6461FACD6EE1186D0182B
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

